CREATE DATABASE inlockGames_DBfirts_manha

USE inlockGames_DBfirts_manha


CREATE TABLE Estudio (
IdEstudio UNIQUEIDENTIFIER PRIMARY KEY,
Nome VARCHAR (100)
)

CREATE TABLE Jogo (
IdJogo UNIQUEIDENTIFIER PRIMARY KEY,
IdEstudio UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Estudio(IdEstudio),
Nome VARCHAR (100) NOT NULL,
Descricao VARCHAR (300),
DataLancamento DATE NOT NULL,
Valor SMALLMONEY NOT NULL
)

CREATE TABLE TipoUsuario (
IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY,
Titulo VARCHAR (100) NOT NULL
)

CREATE TABLE Usuario (
Usuario UNIQUEIDENTIFIER PRIMARY KEY,
IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario) ,
Email VARCHAR (100) NOT NULL,
Senha VARCHAR (20) NOT NULL
)

INSERT INTO Estudio
VALUES (NEWID(),'SENAI') ,(NEWID(),'SESI'),(NEWID(),'SEBRAE')

SELECT * FROM Estudio

INSERT INTO Jogo
VALUES (NEWID(),'B38AA8BA-04A6-43BC-B40F-083F50F72333','ping-pong','Jogo legal','12-05-2015',500),
(NEWID(),'B38AA8BA-04A6-43BC-B40F-083F50F72333','JUCAMON','Caça pokemon','13-05-2006',2.99)

SELECT * FROM Jogo

INSERT INTO TipoUsuario
VALUES (NEWID(),'administrador') ,(NEWID(),'comum')

SELECT * FROM TipoUsuario

INSERT INTO Usuario
VALUES (NEWID(),'E97437A5-6C73-428B-9352-7834D14C66A0','admin@admin.com','admin'),
(NEWID(),'D3BDC234-20D8-49FD-B373-7FABAA71EFC6','user@user.com','user')

SELECT * FROM Usuario


